easyparser
modesty/pdf2json pull request #334
Opened 2024-03-11 10:02 UTC by universalbit-dev

-small updates
---removed some test functions
---commonjs easyparser.js
---- thanks

2024-04-16 17:39 UTC, modesty requested changes
1. package.json and package-lock.json needs to be reverted, it adds unnecessary dependency, contradicts the goal of minimum dependency
2. images/gif folder needs to be deleted to minimize the package size
3. add documentation on easyparser.js, what problem it solves and why it's needed
4. what's the reason to add those JSON file and PDFs?

2024-11-01 15:03 UTC, nicolabaesso reviewed
1. Why FUNDING.yml?
2. I don't know if there is already a license, but LICENSE.md seems the only useful file in this PR.
3. Again, why _config.yml?
4. easyparser.js is just a demo, showing how the library works. Not helpful IMO.
5. gifs are totally pointless
6. I skipped entirely the JSON and PDF files, really not worth it
7. Why removing every reference to this repository? Not cool man
8. Removing all scripts is also nonsense, why would you do that?
9. Updating node version is the only logical thing here, but I'm pretty confident it's not something made on purpose
10. type:module could be left. You removed it because your "easyparser.js" won't compile. You could just rename the file to "easyparser.cjs" (which would not give any value whatsoever).
11. Dependencies is something the original developer already covered
12. Same as point 9 with @types/node and rollup, also why deleting everything else?
13. Removing the url for contributing for bugs, dick move man.
14. readme part confirms it seems like you want to get credit for someone else's work. Not cool.
15. readme lose a lot of useful informations, why?

@modesty (or @modestysn ?) IMO this pull request does not provide any value to the repository, and in some parts I geniuely believe the author is trying to get credit for your (and the contributors) work

2024-11-03 00:19 UTC, modesty requested changes
thanks, @nicolabaesso, I can't make sense of this PR either.

2024-11-03 00:59 UTC, closed without merging

2024-11-03 09:50 UTC, universalbit-dev commented
ok thanks, give me time to understand better


Il giorno dom 3 nov 2024 alle ore 01:59 Modesty Zhang <
***@***.***> ha scritto:

> Closed #334 <https://github.com/modesty/pdf2json/pull/334>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/modesty/pdf2json/pull/334#event-15089437901>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPQOFM6CUTUG4WU2P2RBO3Z6VYPRAVCNFSM6AAAAABEP7KBRGVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVGA4DSNBTG44TAMI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>